<?php

namespace Database\Seeders;

use App\Models\FreeApi;
use App\Models\FreeApiCategory;
use Illuminate\Database\Seeder;

class FreeApiSeeder extends Seeder
{
    public function run(): void
    {
        $catalog = [
            [
                'name' => 'Animals',
                'slug' => 'animals',
                'description' => 'Pets, wildlife and random creature data.',
                'accent' => '#ccff00',
                'apis' => [
                    [
                        'name' => 'Dog API',
                        'slug' => 'dog-api',
                        'url' => 'https://dog.ceo/dog-api/',
                        'base_url' => 'https://dog.ceo/api',
                        'sample_endpoint' => 'https://dog.ceo/api/breeds/image/random',
                        'summary' => 'Random dog images by breed — classic no-auth playground API.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'paw',
                    ],
                    [
                        'name' => 'Cat Facts',
                        'slug' => 'cat-facts',
                        'url' => 'https://catfact.ninja/',
                        'base_url' => 'https://catfact.ninja',
                        'sample_endpoint' => 'https://catfact.ninja/fact',
                        'summary' => 'Random cat facts and breed listings over simple JSON.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'paw',
                    ],
                    [
                        'name' => 'PokéAPI',
                        'slug' => 'pokeapi',
                        'url' => 'https://pokeapi.co/',
                        'base_url' => 'https://pokeapi.co/api/v2',
                        'sample_endpoint' => 'https://pokeapi.co/api/v2/pokemon/ditto',
                        'summary' => 'Complete Pokémon encyclopedia with sprites, moves and types.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'zap',
                    ],
                ],
            ],
            [
                'name' => 'Development',
                'slug' => 'development',
                'description' => 'HTTP playgrounds, placeholders and tooling APIs.',
                'accent' => '#7CFFB2',
                'apis' => [
                    [
                        'name' => 'JSONPlaceholder',
                        'slug' => 'jsonplaceholder',
                        'url' => 'https://jsonplaceholder.typicode.com/',
                        'base_url' => 'https://jsonplaceholder.typicode.com',
                        'sample_endpoint' => 'https://jsonplaceholder.typicode.com/posts/1',
                        'summary' => 'Fake REST API for prototypes — posts, users, todos.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'braces',
                    ],
                    [
                        'name' => 'httpbin',
                        'slug' => 'httpbin',
                        'url' => 'https://httpbin.org/',
                        'base_url' => 'https://httpbin.org',
                        'sample_endpoint' => 'https://httpbin.org/get',
                        'summary' => 'Echo HTTP requests — headers, auth, status codes for debugging.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'code',
                    ],
                    [
                        'name' => 'ReqRes',
                        'slug' => 'reqres',
                        'url' => 'https://reqres.in/',
                        'base_url' => 'https://reqres.in/api',
                        'sample_endpoint' => 'https://reqres.in/api/users?page=2',
                        'summary' => 'Hosted REST sample for login, pagination and CRUD demos.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'code',
                    ],
                    [
                        'name' => 'DummyJSON',
                        'slug' => 'dummyjson',
                        'url' => 'https://dummyjson.com/',
                        'base_url' => 'https://dummyjson.com',
                        'sample_endpoint' => 'https://dummyjson.com/products/1',
                        'summary' => 'Products, carts, auth and image placeholders for frontend mocks.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'package',
                    ],
                ],
            ],
            [
                'name' => 'Finance',
                'slug' => 'finance',
                'description' => 'Crypto, FX and market snapshots.',
                'accent' => '#D4FF4A',
                'apis' => [
                    [
                        'name' => 'CoinGecko',
                        'slug' => 'coingecko',
                        'url' => 'https://www.coingecko.com/en/api',
                        'base_url' => 'https://api.coingecko.com/api/v3',
                        'sample_endpoint' => 'https://api.coingecko.com/api/v3/ping',
                        'summary' => 'Crypto prices, markets and coin metadata — generous free tier.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'coins',
                    ],
                    [
                        'name' => 'Frankfurter',
                        'slug' => 'frankfurter',
                        'url' => 'https://www.frankfurter.app/',
                        'base_url' => 'https://api.frankfurter.app',
                        'sample_endpoint' => 'https://api.frankfurter.app/latest?from=EUR',
                        'summary' => 'ECB-based FX rates — no key, simple JSON.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'coins',
                    ],
                ],
            ],
            [
                'name' => 'Geolocation',
                'slug' => 'geolocation',
                'description' => 'IP, maps, countries and places.',
                'accent' => '#9BFF57',
                'apis' => [
                    [
                        'name' => 'REST Countries',
                        'slug' => 'rest-countries',
                        'url' => 'https://restcountries.com/',
                        'base_url' => 'https://restcountries.com/v3.1',
                        'sample_endpoint' => 'https://restcountries.com/v3.1/name/hungary',
                        'summary' => 'Country flags, capitals, currencies and borders.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'globe',
                    ],
                    [
                        'name' => 'ipify',
                        'slug' => 'ipify',
                        'url' => 'https://www.ipify.org/',
                        'base_url' => 'https://api.ipify.org',
                        'sample_endpoint' => 'https://api.ipify.org?format=json',
                        'summary' => 'Minimal public IP lookup — perfect for client diagnostics.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'network',
                    ],
                    [
                        'name' => 'Zippopotam',
                        'slug' => 'zippopotam',
                        'url' => 'https://www.zippopotam.us/',
                        'base_url' => 'https://api.zippopotam.us',
                        'sample_endpoint' => 'https://api.zippopotam.us/us/90210',
                        'summary' => 'Postal code → city/state lookup for many countries.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'map',
                    ],
                ],
            ],
            [
                'name' => 'Weather',
                'slug' => 'weather',
                'description' => 'Forecast and climate without a paywall.',
                'accent' => '#B8FF66',
                'apis' => [
                    [
                        'name' => 'Open-Meteo',
                        'slug' => 'open-meteo',
                        'url' => 'https://open-meteo.com/',
                        'base_url' => 'https://api.open-meteo.com/v1',
                        'sample_endpoint' => 'https://api.open-meteo.com/v1/forecast?latitude=47.5&longitude=19.04&current_weather=true',
                        'summary' => 'High-resolution weather — free for non-commercial use, no key.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'cloud',
                    ],
                    [
                        'name' => 'wttr.in',
                        'slug' => 'wttr-in',
                        'url' => 'https://wttr.in/:help',
                        'base_url' => 'https://wttr.in',
                        'sample_endpoint' => 'https://wttr.in/Budapest?format=j1',
                        'summary' => 'Curl-friendly weather with JSON and ASCII modes.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'cloud',
                    ],
                ],
            ],
            [
                'name' => 'Entertainment',
                'slug' => 'entertainment',
                'description' => 'Jokes, quotes, games and boredom killers.',
                'accent' => '#7CFFB2',
                'apis' => [
                    [
                        'name' => 'JokeAPI',
                        'slug' => 'jokeapi',
                        'url' => 'https://sv443.net/jokeapi/v2/',
                        'base_url' => 'https://v2.jokeapi.dev',
                        'sample_endpoint' => 'https://v2.jokeapi.dev/joke/Any',
                        'summary' => 'Filtered jokes by category, type and blacklist flags.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'smile',
                    ],
                    [
                        'name' => 'Bored API',
                        'slug' => 'bored-api',
                        'url' => 'https://www.boredapi.com/',
                        'base_url' => 'https://www.boredapi.com/api',
                        'sample_endpoint' => 'https://www.boredapi.com/api/activity',
                        'summary' => 'Suggests random activities when you need inspiration.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'zap',
                    ],
                    [
                        'name' => 'Advice Slip',
                        'slug' => 'advice-slip',
                        'url' => 'https://api.adviceslip.com/',
                        'base_url' => 'https://api.adviceslip.com',
                        'sample_endpoint' => 'https://api.adviceslip.com/advice',
                        'summary' => 'Tiny advice generator — one slip per request.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'message',
                    ],
                    [
                        'name' => 'Rick and Morty',
                        'slug' => 'rick-and-morty',
                        'url' => 'https://rickandmortyapi.com/',
                        'base_url' => 'https://rickandmortyapi.com/api',
                        'sample_endpoint' => 'https://rickandmortyapi.com/api/character/1',
                        'summary' => 'Characters, locations and episodes from the show.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'tv',
                    ],
                ],
            ],
            [
                'name' => 'Science',
                'slug' => 'science',
                'description' => 'Space, astronomy and open research feeds.',
                'accent' => '#ccff00',
                'apis' => [
                    [
                        'name' => 'NASA APOD',
                        'slug' => 'nasa-apod',
                        'url' => 'https://api.nasa.gov/',
                        'base_url' => 'https://api.nasa.gov/planetary',
                        'sample_endpoint' => 'https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY',
                        'summary' => 'Astronomy Picture of the Day — DEMO_KEY works for light use.',
                        'auth' => 'apiKey',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'rocket',
                    ],
                    [
                        'name' => 'SpaceX',
                        'slug' => 'spacex',
                        'url' => 'https://github.com/r-spacex/SpaceX-API',
                        'base_url' => 'https://api.spacexdata.com/v5',
                        'sample_endpoint' => 'https://api.spacexdata.com/v5/launches/latest',
                        'summary' => 'Launches, rockets and crew data from SpaceX open API.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'rocket',
                    ],
                    [
                        'name' => 'Open Library',
                        'slug' => 'open-library',
                        'url' => 'https://openlibrary.org/developers/api',
                        'base_url' => 'https://openlibrary.org',
                        'sample_endpoint' => 'https://openlibrary.org/search.json?q=lord+of+the+rings',
                        'summary' => 'Book search, covers and works metadata.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'book',
                    ],
                ],
            ],
            [
                'name' => 'Food',
                'slug' => 'food',
                'description' => 'Recipes, meals and drinks.',
                'accent' => '#D4FF4A',
                'apis' => [
                    [
                        'name' => 'TheMealDB',
                        'slug' => 'themealdb',
                        'url' => 'https://www.themealdb.com/api.php',
                        'base_url' => 'https://www.themealdb.com/api/json/v1/1',
                        'sample_endpoint' => 'https://www.themealdb.com/api/json/v1/1/random.php',
                        'summary' => 'Meal recipes with images — free test key built into paths.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'utensils',
                    ],
                    [
                        'name' => 'TheCocktailDB',
                        'slug' => 'thecocktaildb',
                        'url' => 'https://www.thecocktaildb.com/api.php',
                        'base_url' => 'https://www.thecocktaildb.com/api/json/v1/1',
                        'sample_endpoint' => 'https://www.thecocktaildb.com/api/json/v1/1/random.php',
                        'summary' => 'Cocktail recipes twin of TheMealDB.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'utensils',
                    ],
                ],
            ],
            [
                'name' => 'Utilities',
                'slug' => 'utilities',
                'description' => 'Dictionaries, users and everyday helpers.',
                'accent' => '#9BFF57',
                'apis' => [
                    [
                        'name' => 'Dictionary API',
                        'slug' => 'dictionary-api',
                        'url' => 'https://dictionaryapi.dev/',
                        'base_url' => 'https://api.dictionaryapi.dev/api/v2',
                        'sample_endpoint' => 'https://api.dictionaryapi.dev/api/v2/entries/en/hello',
                        'summary' => 'Free English dictionary with phonetics and meanings.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'book',
                    ],
                    [
                        'name' => 'Random User',
                        'slug' => 'random-user',
                        'url' => 'https://randomuser.me/',
                        'base_url' => 'https://randomuser.me/api',
                        'sample_endpoint' => 'https://randomuser.me/api/',
                        'summary' => 'Realistic fake user profiles for UI seeding.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'users',
                    ],
                    [
                        'name' => 'Universities API',
                        'slug' => 'universities-api',
                        'url' => 'https://github.com/Hipo/university-domains-list',
                        'base_url' => 'http://universities.hipolabs.com',
                        'sample_endpoint' => 'http://universities.hipolabs.com/search?country=Hungary',
                        'summary' => 'University names and domains by country.',
                        'auth' => 'none',
                        'https' => false,
                        'cors' => true,
                        'icon' => 'graduation',
                    ],
                    [
                        'name' => 'Agify',
                        'slug' => 'agify',
                        'url' => 'https://agify.io/',
                        'base_url' => 'https://api.agify.io',
                        'sample_endpoint' => 'https://api.agify.io?name=michael',
                        'summary' => 'Predict age from a first name — fun demo endpoint.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'users',
                    ],
                ],
            ],
        ];

        $keepSlugs = [];

        foreach ($catalog as $categoryIndex => $entry) {
            $category = FreeApiCategory::query()->updateOrCreate(
                ['slug' => $entry['slug']],
                [
                    'name' => $entry['name'],
                    'description' => $entry['description'],
                    'accent' => $entry['accent'],
                    'sort_order' => $categoryIndex + 1,
                ],
            );

            foreach ($entry['apis'] as $apiIndex => $api) {
                $keepSlugs[] = $api['slug'];

                FreeApi::query()->updateOrCreate(
                    ['slug' => $api['slug']],
                    [
                        'free_api_category_id' => $category->id,
                        'name' => $api['name'],
                        'url' => $api['url'],
                        'base_url' => $api['base_url'],
                        'sample_endpoint' => $api['sample_endpoint'],
                        'summary' => $api['summary'],
                        'auth' => $api['auth'],
                        'https' => $api['https'],
                        'cors' => $api['cors'],
                        'icon' => $api['icon'],
                        'sort_order' => $apiIndex + 1,
                        'is_active' => true,
                    ],
                );
            }
        }

        FreeApi::query()
            ->whereNotIn('slug', $keepSlugs)
            ->update(['is_active' => false]);
    }
}
