<?php

namespace Database\Seeders;

use App\Models\FreeApi;
use App\Models\FreeApiCategory;
use Illuminate\Database\Seeder;

class FreeApiSeeder extends Seeder
{
    public function run(): void
    {
        $catalog = [
            [
                'name' => 'Animals',
                'slug' => 'animals',
                'description' => 'Pets, wildlife and random creature data.',
                'accent' => '#ccff00',
                'apis' => [
                    [
                        'name' => 'Dog API',
                        'slug' => 'dog-api',
                        'url' => 'https://dog.ceo/dog-api/',
                        'base_url' => 'https://dog.ceo/api',
                        'sample_endpoint' => 'https://dog.ceo/api/breeds/image/random',
                        'summary' => 'Random dog images by breed — classic no-auth playground API.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'paw',
                    ],
                    [
                        'name' => 'Cat Facts',
                        'slug' => 'cat-facts',
                        'url' => 'https://catfact.ninja/',
                        'base_url' => 'https://catfact.ninja',
                        'sample_endpoint' => 'https://catfact.ninja/fact',
                        'summary' => 'Random cat facts and breed listings over simple JSON.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'paw',
                    ],
                    [
                        'name' => 'PokéAPI',
                        'slug' => 'pokeapi',
                        'url' => 'https://pokeapi.co/',
                        'base_url' => 'https://pokeapi.co/api/v2',
                        'sample_endpoint' => 'https://pokeapi.co/api/v2/pokemon/ditto',
                        'summary' => 'Complete Pokémon encyclopedia with sprites, moves and types.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'zap',
                    ],
                    [
                        'name' => 'RandomFox',
                        'slug' => 'randomfox',
                        'url' => 'https://randomfox.ca/',
                        'base_url' => 'https://randomfox.ca',
                        'sample_endpoint' => 'https://randomfox.ca/floof/',
                        'summary' => 'Random fox photos — simple JSON image URL from public-apis.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'paw',
                    ],
                ],
            ],
            [
                'name' => 'Development',
                'slug' => 'development',
                'description' => 'HTTP playgrounds, placeholders and tooling APIs.',
                'accent' => '#7CFFB2',
                'apis' => [
                    [
                        'name' => 'JSONPlaceholder',
                        'slug' => 'jsonplaceholder',
                        'url' => 'https://jsonplaceholder.typicode.com/',
                        'base_url' => 'https://jsonplaceholder.typicode.com',
                        'sample_endpoint' => 'https://jsonplaceholder.typicode.com/posts/1',
                        'summary' => 'Fake REST API for prototypes — posts, users, todos.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'braces',
                    ],
                    [
                        'name' => 'httpbin',
                        'slug' => 'httpbin',
                        'url' => 'https://httpbin.org/',
                        'base_url' => 'https://httpbin.org',
                        'sample_endpoint' => 'https://httpbin.org/get',
                        'summary' => 'Echo HTTP requests — headers, auth, status codes for debugging.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'code',
                    ],
                    [
                        'name' => 'ReqRes',
                        'slug' => 'reqres',
                        'url' => 'https://reqres.in/',
                        'base_url' => 'https://reqres.in/api',
                        'sample_endpoint' => 'https://reqres.in/api/users?page=2',
                        'summary' => 'Hosted REST sample for login, pagination and CRUD demos.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'code',
                    ],
                    [
                        'name' => 'DummyJSON',
                        'slug' => 'dummyjson',
                        'url' => 'https://dummyjson.com/',
                        'base_url' => 'https://dummyjson.com',
                        'sample_endpoint' => 'https://dummyjson.com/products/1',
                        'summary' => 'Products, carts, auth and image placeholders for frontend mocks.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'package',
                    ],
                    [
                        'name' => 'Public APIs',
                        'slug' => 'public-apis',
                        'url' => 'https://github.com/public-apis/public-apis',
                        'base_url' => 'https://api.github.com',
                        'sample_endpoint' => 'https://api.github.com/repos/public-apis/public-apis',
                        'summary' => 'Community-curated catalog of free public APIs — source list for this registry.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'globe',
                    ],
                    [
                        'name' => 'Icanhazip',
                        'slug' => 'icanhazip',
                        'url' => 'https://major.io/icanhazip-com-faq/',
                        'base_url' => 'https://icanhazip.com',
                        'sample_endpoint' => 'https://icanhazip.com/',
                        'summary' => 'Returns your public IP as plain text — zero-config client diagnostics.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'network',
                    ],
                    [
                        'name' => 'QuickChart',
                        'slug' => 'quickchart',
                        'url' => 'https://quickchart.io/',
                        'base_url' => 'https://quickchart.io',
                        'sample_endpoint' => 'https://quickchart.io/chart?c=%7Btype%3A%27bar%27%2Cdata%3A%7Blabels%3A%5B%27Q1%27%5D%2Cdatasets%3A%5B%7Bdata%3A%5B42%5D%7D%5D%7D%7D',
                        'summary' => 'Generate chart and graph images from Chart.js config in the URL.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'braces',
                    ],
                ],
            ],
            [
                'name' => 'Finance',
                'slug' => 'finance',
                'description' => 'Crypto, FX and market snapshots.',
                'accent' => '#D4FF4A',
                'apis' => [
                    [
                        'name' => 'CoinGecko',
                        'slug' => 'coingecko',
                        'url' => 'https://www.coingecko.com/en/api',
                        'base_url' => 'https://api.coingecko.com/api/v3',
                        'sample_endpoint' => 'https://api.coingecko.com/api/v3/ping',
                        'summary' => 'Crypto prices, markets and coin metadata — generous free tier.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'coins',
                    ],
                    [
                        'name' => 'Frankfurter',
                        'slug' => 'frankfurter',
                        'url' => 'https://www.frankfurter.app/',
                        'base_url' => 'https://api.frankfurter.app',
                        'sample_endpoint' => 'https://api.frankfurter.app/latest?from=EUR',
                        'summary' => 'ECB-based FX rates — no key, simple JSON.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'coins',
                    ],
                    [
                        'name' => 'ExchangeRate Host',
                        'slug' => 'exchangerate-host',
                        'url' => 'https://exchangerate.host/',
                        'base_url' => 'https://api.exchangerate.host',
                        'sample_endpoint' => 'https://api.exchangerate.host/latest?base=USD',
                        'summary' => 'Real-time and historical foreign exchange rates — no API key.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'coins',
                    ],
                ],
            ],
            [
                'name' => 'Geolocation',
                'slug' => 'geolocation',
                'description' => 'IP, maps, countries and places.',
                'accent' => '#9BFF57',
                'apis' => [
                    [
                        'name' => 'REST Countries',
                        'slug' => 'rest-countries',
                        'url' => 'https://restcountries.com/',
                        'base_url' => 'https://restcountries.com/v3.1',
                        'sample_endpoint' => 'https://restcountries.com/v3.1/name/hungary',
                        'summary' => 'Country flags, capitals, currencies and borders.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'globe',
                    ],
                    [
                        'name' => 'ipify',
                        'slug' => 'ipify',
                        'url' => 'https://www.ipify.org/',
                        'base_url' => 'https://api.ipify.org',
                        'sample_endpoint' => 'https://api.ipify.org?format=json',
                        'summary' => 'Minimal public IP lookup — perfect for client diagnostics.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'network',
                    ],
                    [
                        'name' => 'Zippopotam',
                        'slug' => 'zippopotam',
                        'url' => 'https://www.zippopotam.us/',
                        'base_url' => 'https://api.zippopotam.us',
                        'sample_endpoint' => 'https://api.zippopotam.us/us/90210',
                        'summary' => 'Postal code → city/state lookup for many countries.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'map',
                    ],
                    [
                        'name' => 'Nominatim',
                        'slug' => 'nominatim',
                        'url' => 'https://nominatim.org/release-docs/latest/api/Search/',
                        'base_url' => 'https://nominatim.openstreetmap.org',
                        'sample_endpoint' => 'https://nominatim.openstreetmap.org/search?q=Budapest&format=json&limit=1',
                        'summary' => 'OpenStreetMap geocoding — forward search by place name.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'map',
                    ],
                ],
            ],
            [
                'name' => 'Weather',
                'slug' => 'weather',
                'description' => 'Forecast and climate without a paywall.',
                'accent' => '#B8FF66',
                'apis' => [
                    [
                        'name' => 'Open-Meteo',
                        'slug' => 'open-meteo',
                        'url' => 'https://open-meteo.com/',
                        'base_url' => 'https://api.open-meteo.com/v1',
                        'sample_endpoint' => 'https://api.open-meteo.com/v1/forecast?latitude=47.5&longitude=19.04&current_weather=true',
                        'summary' => 'High-resolution weather — free for non-commercial use, no key.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'cloud',
                    ],
                    [
                        'name' => 'wttr.in',
                        'slug' => 'wttr-in',
                        'url' => 'https://wttr.in/:help',
                        'base_url' => 'https://wttr.in',
                        'sample_endpoint' => 'https://wttr.in/Budapest?format=j1',
                        'summary' => 'Curl-friendly weather with JSON and ASCII modes.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'cloud',
                    ],
                ],
            ],
            [
                'name' => 'Entertainment',
                'slug' => 'entertainment',
                'description' => 'Jokes, quotes, games and boredom killers.',
                'accent' => '#7CFFB2',
                'apis' => [
                    [
                        'name' => 'JokeAPI',
                        'slug' => 'jokeapi',
                        'url' => 'https://sv443.net/jokeapi/v2/',
                        'base_url' => 'https://v2.jokeapi.dev',
                        'sample_endpoint' => 'https://v2.jokeapi.dev/joke/Any',
                        'summary' => 'Filtered jokes by category, type and blacklist flags.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'smile',
                    ],
                    [
                        'name' => 'Bored API',
                        'slug' => 'bored-api',
                        'url' => 'https://www.boredapi.com/',
                        'base_url' => 'https://www.boredapi.com/api',
                        'sample_endpoint' => 'https://www.boredapi.com/api/activity',
                        'summary' => 'Suggests random activities when you need inspiration.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'zap',
                    ],
                    [
                        'name' => 'Advice Slip',
                        'slug' => 'advice-slip',
                        'url' => 'https://api.adviceslip.com/',
                        'base_url' => 'https://api.adviceslip.com',
                        'sample_endpoint' => 'https://api.adviceslip.com/advice',
                        'summary' => 'Tiny advice generator — one slip per request.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'message',
                    ],
                    [
                        'name' => 'Rick and Morty',
                        'slug' => 'rick-and-morty',
                        'url' => 'https://rickandmortyapi.com/',
                        'base_url' => 'https://rickandmortyapi.com/api',
                        'sample_endpoint' => 'https://rickandmortyapi.com/api/character/1',
                        'summary' => 'Characters, locations and episodes from the show.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'tv',
                    ],
                ],
            ],
            [
                'name' => 'Science',
                'slug' => 'science',
                'description' => 'Space, astronomy and open research feeds.',
                'accent' => '#ccff00',
                'apis' => [
                    [
                        'name' => 'NASA APOD',
                        'slug' => 'nasa-apod',
                        'url' => 'https://api.nasa.gov/',
                        'base_url' => 'https://api.nasa.gov/planetary',
                        'sample_endpoint' => 'https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY',
                        'summary' => 'Astronomy Picture of the Day — DEMO_KEY works for light use.',
                        'auth' => 'apiKey',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'rocket',
                    ],
                    [
                        'name' => 'SpaceX',
                        'slug' => 'spacex',
                        'url' => 'https://github.com/r-spacex/SpaceX-API',
                        'base_url' => 'https://api.spacexdata.com/v5',
                        'sample_endpoint' => 'https://api.spacexdata.com/v5/launches/latest',
                        'summary' => 'Launches, rockets and crew data from SpaceX open API.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'rocket',
                    ],
                    [
                        'name' => 'Open Library',
                        'slug' => 'open-library',
                        'url' => 'https://openlibrary.org/developers/api',
                        'base_url' => 'https://openlibrary.org',
                        'sample_endpoint' => 'https://openlibrary.org/search.json?q=lord+of+the+rings',
                        'summary' => 'Book search, covers and works metadata.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'book',
                    ],
                    [
                        'name' => 'Launch Library 2',
                        'slug' => 'launch-library-2',
                        'url' => 'https://thespacedevs.com/llapi',
                        'base_url' => 'https://ll.thespacedevs.com/2.2.0',
                        'sample_endpoint' => 'https://ll.thespacedevs.com/2.2.0/launch/upcoming/?limit=1',
                        'summary' => 'Upcoming and historical spaceflight launches from The Space Devs.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'rocket',
                    ],
                    [
                        'name' => 'OpenAlex',
                        'slug' => 'openalex',
                        'url' => 'https://docs.openalex.org/',
                        'base_url' => 'https://api.openalex.org',
                        'sample_endpoint' => 'https://api.openalex.org/works?search=machine+learning&per-page=1',
                        'summary' => 'Open catalog of scholarly works, authors, institutions and concepts.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'book',
                    ],
                    [
                        'name' => 'USGS Earthquake',
                        'slug' => 'usgs-earthquake',
                        'url' => 'https://earthquake.usgs.gov/fdsnws/event/1/',
                        'base_url' => 'https://earthquake.usgs.gov/fdsnws/event/1',
                        'sample_endpoint' => 'https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&limit=1',
                        'summary' => 'Real-time earthquake events worldwide in GeoJSON.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'globe',
                    ],
                    [
                        'name' => 'Sunrise-Sunset',
                        'slug' => 'sunrise-sunset',
                        'url' => 'https://sunrise-sunset.org/api',
                        'base_url' => 'https://api.sunrise-sunset.org',
                        'sample_endpoint' => 'https://api.sunrise-sunset.org/json?lat=47.5&lng=19.04',
                        'summary' => 'Sunrise and sunset times for any latitude/longitude.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'cloud',
                    ],
                ],
            ],
            [
                'name' => 'Food',
                'slug' => 'food',
                'description' => 'Recipes, meals and drinks.',
                'accent' => '#D4FF4A',
                'apis' => [
                    [
                        'name' => 'TheMealDB',
                        'slug' => 'themealdb',
                        'url' => 'https://www.themealdb.com/api.php',
                        'base_url' => 'https://www.themealdb.com/api/json/v1/1',
                        'sample_endpoint' => 'https://www.themealdb.com/api/json/v1/1/random.php',
                        'summary' => 'Meal recipes with images — free test key built into paths.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'utensils',
                    ],
                    [
                        'name' => 'TheCocktailDB',
                        'slug' => 'thecocktaildb',
                        'url' => 'https://www.thecocktaildb.com/api.php',
                        'base_url' => 'https://www.thecocktaildb.com/api/json/v1/1',
                        'sample_endpoint' => 'https://www.thecocktaildb.com/api/json/v1/1/random.php',
                        'summary' => 'Cocktail recipes twin of TheMealDB.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'utensils',
                    ],
                ],
            ],
            [
                'name' => 'Utilities',
                'slug' => 'utilities',
                'description' => 'Dictionaries, users and everyday helpers.',
                'accent' => '#9BFF57',
                'apis' => [
                    [
                        'name' => 'Dictionary API',
                        'slug' => 'dictionary-api',
                        'url' => 'https://dictionaryapi.dev/',
                        'base_url' => 'https://api.dictionaryapi.dev/api/v2',
                        'sample_endpoint' => 'https://api.dictionaryapi.dev/api/v2/entries/en/hello',
                        'summary' => 'Free English dictionary with phonetics and meanings.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'book',
                    ],
                    [
                        'name' => 'Random User',
                        'slug' => 'random-user',
                        'url' => 'https://randomuser.me/',
                        'base_url' => 'https://randomuser.me/api',
                        'sample_endpoint' => 'https://randomuser.me/api/',
                        'summary' => 'Realistic fake user profiles for UI seeding.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'users',
                    ],
                    [
                        'name' => 'Universities API',
                        'slug' => 'universities-api',
                        'url' => 'https://github.com/Hipo/university-domains-list',
                        'base_url' => 'http://universities.hipolabs.com',
                        'sample_endpoint' => 'http://universities.hipolabs.com/search?country=Hungary',
                        'summary' => 'University names and domains by country.',
                        'auth' => 'none',
                        'https' => false,
                        'cors' => true,
                        'icon' => 'graduation',
                    ],
                    [
                        'name' => 'Agify',
                        'slug' => 'agify',
                        'url' => 'https://agify.io/',
                        'base_url' => 'https://api.agify.io',
                        'sample_endpoint' => 'https://api.agify.io?name=michael',
                        'summary' => 'Predict age from a first name — fun demo endpoint.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'users',
                    ],
                    [
                        'name' => 'Genderize.io',
                        'slug' => 'genderize',
                        'url' => 'https://genderize.io/',
                        'base_url' => 'https://api.genderize.io',
                        'sample_endpoint' => 'https://api.genderize.io?name=robin',
                        'summary' => 'Estimate gender from a first name — sibling of Agify/Nationalize.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'users',
                    ],
                    [
                        'name' => 'Nationalize.io',
                        'slug' => 'nationalize',
                        'url' => 'https://nationalize.io/',
                        'base_url' => 'https://api.nationalize.io',
                        'sample_endpoint' => 'https://api.nationalize.io?name=nathaniel',
                        'summary' => 'Estimate nationality probabilities from a first name.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'globe',
                    ],
                ],
            ],
            [
                'name' => 'Anime',
                'slug' => 'anime',
                'description' => 'Anime metadata, quotes and Ghibli filmography.',
                'accent' => '#FF8AD4',
                'apis' => [
                    [
                        'name' => 'Studio Ghibli',
                        'slug' => 'studio-ghibli',
                        'url' => 'https://ghibliapi.vercel.app',
                        'base_url' => 'https://ghibliapi.vercel.app',
                        'sample_endpoint' => 'https://ghibliapi.vercel.app/films',
                        'summary' => 'Films, characters and locations from Studio Ghibli works.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'tv',
                    ],
                    [
                        'name' => 'Jikan',
                        'slug' => 'jikan',
                        'url' => 'https://jikan.moe/',
                        'base_url' => 'https://api.jikan.moe/v4',
                        'sample_endpoint' => 'https://api.jikan.moe/v4/anime/1',
                        'summary' => 'Unofficial MyAnimeList API — anime, manga, characters and search.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'tv',
                    ],
                ],
            ],
            [
                'name' => 'Games & Comics',
                'slug' => 'games-comics',
                'description' => 'Trivia, free games and tabletop reference APIs.',
                'accent' => '#7CFFB2',
                'apis' => [
                    [
                        'name' => 'Open Trivia DB',
                        'slug' => 'opentdb',
                        'url' => 'https://opentdb.com/api_config.php',
                        'base_url' => 'https://opentdb.com',
                        'sample_endpoint' => 'https://opentdb.com/api.php?amount=1',
                        'summary' => 'Multiple-choice trivia questions across categories and difficulty.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'zap',
                    ],
                    [
                        'name' => 'FreeToGame',
                        'slug' => 'freetogame',
                        'url' => 'https://www.freetogame.com/api-doc',
                        'base_url' => 'https://www.freetogame.com/api',
                        'sample_endpoint' => 'https://www.freetogame.com/api/games',
                        'summary' => 'Free-to-play PC and browser games database with filters.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'package',
                    ],
                    [
                        'name' => 'Open5e',
                        'slug' => 'open5e',
                        'url' => 'https://open5e.com/',
                        'base_url' => 'https://api.open5e.com/v2',
                        'sample_endpoint' => 'https://api.open5e.com/v2/spells/?limit=1',
                        'summary' => 'D&D 5e SRD spells, monsters and equipment as JSON.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'book',
                    ],
                    [
                        'name' => 'Chuck Norris Facts',
                        'slug' => 'chuck-norris',
                        'url' => 'https://api.chucknorris.io/',
                        'base_url' => 'https://api.chucknorris.io',
                        'sample_endpoint' => 'https://api.chucknorris.io/jokes/random',
                        'summary' => 'Random Chuck Norris joke JSON — classic dev meme API.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'smile',
                    ],
                ],
            ],
            [
                'name' => 'News',
                'slug' => 'news',
                'description' => 'Tech headlines and space industry feeds.',
                'accent' => '#B8FF66',
                'apis' => [
                    [
                        'name' => 'Spaceflight News',
                        'slug' => 'spaceflight-news',
                        'url' => 'https://spaceflightnewsapi.net',
                        'base_url' => 'https://api.spaceflightnewsapi.net/v4',
                        'sample_endpoint' => 'https://api.spaceflightnewsapi.net/v4/articles/?limit=1',
                        'summary' => 'Spaceflight-related news articles and blogs aggregated in JSON.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'rocket',
                    ],
                    [
                        'name' => 'Hacker News',
                        'slug' => 'hacker-news',
                        'url' => 'https://github.com/HackerNews/API',
                        'base_url' => 'https://hacker-news.firebaseio.com/v0',
                        'sample_endpoint' => 'https://hacker-news.firebaseio.com/v0/topstories.json',
                        'summary' => 'Firebase JSON API for HN story, comment and user IDs.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'code',
                    ],
                ],
            ],
            [
                'name' => 'Art & Design',
                'slug' => 'art-design',
                'description' => 'Museum collections, icons and placeholder imagery.',
                'accent' => '#FFB347',
                'apis' => [
                    [
                        'name' => 'Art Institute of Chicago',
                        'slug' => 'art-institute-chicago',
                        'url' => 'https://api.artic.edu/docs/',
                        'base_url' => 'https://api.artic.edu/api/v1',
                        'sample_endpoint' => 'https://api.artic.edu/api/v1/artworks?limit=1',
                        'summary' => 'Open access artworks from the Art Institute of Chicago.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'globe',
                    ],
                    [
                        'name' => 'Iconify',
                        'slug' => 'iconify',
                        'url' => 'https://iconify.design/docs/api/',
                        'base_url' => 'https://api.iconify.design',
                        'sample_endpoint' => 'https://api.iconify.design/search?query=home',
                        'summary' => 'Search 200+ open-source icon sets and fetch SVG by name.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'package',
                    ],
                    [
                        'name' => 'Lorem Picsum',
                        'slug' => 'lorem-picsum',
                        'url' => 'https://picsum.photos/',
                        'base_url' => 'https://picsum.photos',
                        'sample_endpoint' => 'https://picsum.photos/v2/list?page=1&limit=1',
                        'summary' => 'Placeholder photos — list metadata or hotlink sized images.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'globe',
                    ],
                ],
            ],
            [
                'name' => 'Music',
                'slug' => 'music',
                'description' => 'Internet radio and open music metadata.',
                'accent' => '#D4FF4A',
                'apis' => [
                    [
                        'name' => 'Radio Browser',
                        'slug' => 'radio-browser',
                        'url' => 'https://api.radio-browser.info/',
                        'base_url' => 'https://de1.api.radio-browser.info/json',
                        'sample_endpoint' => 'https://de1.api.radio-browser.info/json/stations/bycountry/us?limit=1',
                        'summary' => 'Community-maintained list of internet radio stations worldwide.',
                        'auth' => 'none',
                        'https' => true,
                        'cors' => true,
                        'icon' => 'tv',
                    ],
                ],
            ],
        ];

        $keepSlugs = [];

        foreach ($catalog as $categoryIndex => $entry) {
            $category = FreeApiCategory::query()->updateOrCreate(
                ['slug' => $entry['slug']],
                [
                    'name' => $entry['name'],
                    'description' => $entry['description'],
                    'accent' => $entry['accent'],
                    'sort_order' => $categoryIndex + 1,
                ],
            );

            foreach ($entry['apis'] as $apiIndex => $api) {
                $keepSlugs[] = $api['slug'];

                FreeApi::query()->updateOrCreate(
                    ['slug' => $api['slug']],
                    [
                        'free_api_category_id' => $category->id,
                        'name' => $api['name'],
                        'url' => $api['url'],
                        'base_url' => $api['base_url'],
                        'sample_endpoint' => $api['sample_endpoint'],
                        'summary' => $api['summary'],
                        'auth' => $api['auth'],
                        'https' => $api['https'],
                        'cors' => $api['cors'],
                        'icon' => $api['icon'],
                        'sort_order' => $apiIndex + 1,
                        'is_active' => true,
                    ],
                );
            }
        }

        FreeApi::query()
            ->whereNotIn('slug', $keepSlugs)
            ->update(['is_active' => false]);
    }
}
